### PR TITLE
CIP [0014]: Add new exchange function to allow buying fixed amount of tokens for maximum price

### PR DESCRIPTION
**Pull request by zviadm**

### CODE REVIEW

**Comment by asaj** [comment]
Wdyt of the following function signatures, and deprecating the `exchange` function?

```
function buy(uint256 amount, uint256 minSellAmount, bool buyGold);
function sell(uint256 amount, uint256 minBuyAmount, bool sellGold);
```

**Comment by zviadm** [comment]
This works, and it should cover all the use cases that I mentioned in the CIP.

**Comment by tkporter** [comment]
@asaj PR will be out soon

Shouldn't `buy` enforce a maxSellAmount instead of minSellAmount?
```
function buy(uint256 amount, uint256 maxSellAmount, bool buyGold);
```

**Comment by tkporter** [comment]
PR is up at https://github.com/celo-org/celo-monorepo/pull/4580

**Comment by martinvol** [comment]
Shall we close as https://github.com/celo-org/celo-monorepo/pull/4580 got merged?

**Comment by nambrot** [comment]
Agreed @tkporter ?

**Comment by prestwich** [comment]
Closing as obsolete

**Comment by tkporter** [comment]
Whoops didn't see this-- is there a reason why we'd close instead of merge?

**Comment by prestwich** [comment]
hey @tkporter trying to clean up stale PRs a bit. I asked Nam's opinion but probably ought to have pinged you as well. If this accurately documents current behavior we should clean it up and include it

**Comment by tkporter** [comment]
Yeah this was implemented in https://github.com/celo-org/celo-monorepo/pull/4580. For cleaning up, would that involve making some changes to fit the template https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-template.md?

**Comment by prestwich** [comment]
> For cleaning up, would that involve making some changes to fit the template https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-template.md?

Yes, assuming it's already implemented, this should be 
```
category: Ring 1
type: Standards Track
status: Final
```

**Pull request closed without merging**
